import '../styles/globals.css'
import Head from 'next/head'
import { Button, Grid, Typography,styled, Divider,Drawer, MobileStepper} from "@mui/material";
import { Box } from "@mui/system";
import { makeStyles } from '@mui/styles'
import LargeSidebar from '../components/LargeSidebar';
import SmallSidebar from '../components/SmallSidebar';
import MobileSidebar from '../components/MobileSidebar';
import React, { useState } from 'react';
import {useRouter} from "next/router"
const useStyles = makeStyles({
  dashboardIcon:{
      width:"50px",
      height:"50px",
      marginTop:"5px",
      marginLeft:"6px"
  },
  logoIcon:{
      width:"40px",
      marginTop:"10px"
  },
  smalSidebarIcon:{
      width:"40px",
      cursor:"pointer"
  },
  box:{
      backgroundColor:"#FCD5CE",
      width:"80%",
  },
  backgroundLiquid:{
    position:"absolute",
    zIndex:"0",
    opacity:"75%",
    width:"100%",
    height:"100%"
}
},{ name: "MuiExample_Component" })

const LogoutButton = styled(Button)({
  backgroundColor:"#F8EDEB",
  boxShadow:"none",
  fontWeight:"800",
  color:"#F08080",
  "&:hover":{
      backgroundColor:"#F4978E",
      boxShadow:"none",
      color:"white"
  }
})

const DashboardList = styled(Box)({
  height:"60px",
  width:"100%",
  display:'flex',
  backgroundColor:"#FBC4AB",
  borderRadius:"4px",
  cursor:"pointer"
})
function MyApp({ Component, pageProps }) {
  const classes = useStyles();
  const router = useRouter();
  const [selectList,setSelectList] = useState("")
  console.log(router.pathname)
  const Check=(getSidebar)=>{
    setSelectList(getSidebar)
  }
  return(
  <Box sx={{overflow: "hidden",backgroundColor:"#F8EDEB"}}>
    <Head>
        <title>eWedding | บริการการ์ดอวยพรและซองงานแต่งออนไลน์</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/flatIcon/wedding-ring.png" />
      </Head>
      <Grid container sx={{padding: router.pathname === ("/login") 
      || router.pathname ===("/register") 
      ? false : true 
      && {lg:router.pathname !==("/events") && "calc((100vh - 640px) / 2) calc((100vw - 1300px) / 2)",
      md: router.pathname !==("/events") && "calc((100vh - 640px) / 2) calc((100vw - 1024px) / 2)",sm:"0",xs:"0"},minHeight:"100%"}}>
        {router.pathname === ("/login") || router.pathname ===("/register") || router.pathname ===("/events") ? false : true && <LargeSidebar
          Check={Check}
          selectList={selectList}
        />}
        {router.pathname === ("/login") || router.pathname ===("/register") || router.pathname ===("/events") ? false : true && <SmallSidebar
          Check={Check}
          selectList={selectList}
        />}
        {router.pathname === ("/login") || router.pathname ===("/register") || router.pathname ===("/events") ? false : true && <MobileSidebar
          Check={Check}
        />}
        <Component {...pageProps} />
        
      </Grid>
  </Box>
  )
}

export default MyApp
