import '../styles/globals.css'
import Head from 'next/head'


function MyApp({ Component, pageProps }) {
  return <div>
    <Head>
        <title>eWedding | บริการการ์ดอวยพรและซองงานแต่งออนไลน์</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/flatIcon/wedding-ring.png" />
      </Head>
    <Component {...pageProps} />
  </div>
}

export default MyApp
