import Head from 'next/head'
import { Box, Grid } from '@mui/material'
import Login from '../components/Login'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>eWedding | บริการการ์ดอวยพรและซองงานแต่งออนไลน์</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login/>
    </div>
    
  )
}
