import Head from 'next/head'
import { Box, Grid } from '@mui/material'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>eWedding | บริการการ์ดอวยพรและซองงานแต่งออนไลน์</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/flatIcon/wedding-ring.png" />
      </Head>
    </div>
    
  )
}
